# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'BaiSiBuDeJie-Swift' do
 pod 'SwiftyJSON' 
    pod 'Alamofire'
    pod 'MJRefresh'
    pod 'Kingfisher'
    pod 'DACircularProgress'
end

target 'BaiSiBuDeJie-SwiftUITests' do

end

